### ISSUE TITLE
there is no multiple tabs for opened files in buffer

### ISSUE THREAD

**Issue by rustiever** [adelarsq/neoline.vim#10]
if I open multiple files tabs are not forming, only for active file tab is shown

**Comment by adelarsq** [comment]
Thanks for report @rustiever 
Yes, for how this is a limitation. Not for not possible, but I have little time to work on this at moment.
I will keep this open.

**Comment by adelarsq** [comment]
Closing this for now.
I will add this as feature request to work after rewrite all plugin to Lua.
