### ISSUE TITLE
Add support for coc status line

### ISSUE THREAD

**Issue by rustiever** [adelarsq/neoline.vim#11]
There is function in coc-nvim like nearest function which can show the nearest function relative to cursor

Please add that functionality

**Comment by adelarsq** [comment]
I just added support for this for the TreeSitter. I will also add this support for coc-nvim.

**Comment by adelarsq** [comment]
@rustiever  added support on https://github.com/adelarsq/neoline.vim/commit/b4ecfac8298e75f01b032bd7892959b01a39cc3e
Thanks!
