### ISSUE TITLE
attemp to concatenate a nil value 

### ISSUE THREAD

**Issue by aboueleyes** [adelarsq/neoline.vim#18]
![image](https://user-images.githubusercontent.com/35760882/130163438-6665ae4b-75da-4553-a25f-e15e7bc44b54.png)

**Comment by adelarsq** [comment]
@aboueleyes Thanks for the report!
I did send a change for this rule. Can you test again?

**Comment by aboueleyes** [comment]
the error is gone, but the status line didn't appear?

**Comment by adelarsq** [comment]
> the error is gone, but the status line didn't appear?

@aboueleyes This is not related I think. Can you send your config or the plugins that you are using? Also a screenshot if possible.

**Comment by adelarsq** [comment]
Closing for now. Please reopen the issue if still occurs.
