### ISSUE TITLE
Unknown function

### ISSUE THREAD

**Issue by kdurant** [adelarsq/neoline.vim#3]
![image](https://user-images.githubusercontent.com/2704364/97377176-57459280-18fa-11eb-8814-2e6b46dfe486.png)

**Comment by adelarsq** [comment]
At moment the dependency with vim-signify is mandatory. I will change to be optional.

**Comment by adelarsq** [comment]
Solved at https://github.com/adelarsq/neoline.vim/commit/2584a7c68b07a2d771519f8efb25bc37ddd5a504
Thanks for the report! 🙂
