### ISSUE TITLE
Screenshots in Readme

### ISSUE THREAD

**Issue by ThangaAyyanar** [adelarsq/neoline.vim#4]
Few screenshots of plugin with sample configuration would be great

**Comment by adelarsq** [comment]
Appears the people are already using. I didn't plan to post about this plugin until was "ready", but I'm already using daily.

I will add some screenshots to see the current state.

**Comment by adelarsq** [comment]
I added a screenshot. I will add more when be possible to do some refactoring.
Thanks for the report =)
