### ISSUE TITLE
E5108: Error while calling lua chunk for luaeval(): ...ran/.config/nvim/plugged/neoline.vim/lua/status-line.lua:143: attempt to index field 'lsp' (a nil value)

### ISSUE THREAD

**Issue by rustiever** [adelarsq/neoline.vim#8]
after installation i got this error,
can you point out what i'm doing wrong please

**Comment by adelarsq** [comment]
@rustiever Thanks for the report!
Which Neovim version are you using?

**Comment by adelarsq** [comment]
I updated checking the Neovim version. Can you try?
LSP status is a 0.5 feature. I didn't notice since I'm already using the nightly version.

**Comment by rustiever** [comment]
> @rustiever Thanks for the report!
> Which Neovim version are you using?

NVIM v0.4.4

**Comment by rustiever** [comment]
how to check the lsp version?

**Comment by adelarsq** [comment]
> NVIM v0.4.4

I updated the plugin with support for Neovim 0.4, so features for 0.5 are disabled.

> how to check the lsp version?

It's a Neovim 0.5 feature. You can already use it. It's pretty stable already, but It will take some time to be released.

**Comment by adelarsq** [comment]
I did some testing with Neovim 0.4 and appears that it's solved. I will close this issue for now. Thanks for the report @rustiever
